from __future__ import annotations

from pathlib import Path

import click
from rich.table import Table

from clude.core.scanner import EnvVarUsage, scan_directory
from clude.utils.console import console
from clude.utils.dotenv import parse_dotenv


@click.group()
def env() -> None:
    """Audit and manage environment variables."""


@env.command()
@click.argument("path", default=".", type=click.Path(exists=True, file_okay=False, path_type=Path))
def scan(path: Path) -> None:
    """Scan source files for environment variable usage."""
    with console.status(f"Scanning [bold]{path}[/bold]..."):
        usages = scan_directory(path.resolve())

    if not usages:
        console.print("[yellow]No environment variable usage found.[/yellow]")
        return

    by_name: dict[str, list[EnvVarUsage]] = {}
    for u in usages:
        by_name.setdefault(u.name, []).append(u)

    table = Table(title=f"Environment Variables  {path}", show_lines=False)
    table.add_column("Variable", style="cyan bold", no_wrap=True)
    table.add_column("Refs", justify="right", style="magenta")
    table.add_column("Files", style="dim")

    for name in sorted(by_name):
        refs = by_name[name]
        unique_files = sorted({r.file for r in refs})
        files_str = ", ".join(unique_files[:3])
        if len(unique_files) > 3:
            files_str += f" +{len(unique_files) - 3}"
        table.add_row(name, str(len(refs)), files_str)

    console.print(table)
    console.print(
        f"\n[dim]{len(by_name)} unique variable(s)  {len(usages)} total reference(s)[/dim]"
    )


@env.command()
@click.argument("path", default=".", type=click.Path(exists=True, file_okay=False, path_type=Path))
@click.option("--env-file", default=".env", show_default=True, help="Path to .env file.")
def validate(path: Path, env_file: str) -> None:
    """Validate .env against discovered env var usage."""
    env_file_path = (
        Path(env_file) if Path(env_file).is_absolute() else path.resolve() / env_file
    )

    with console.status("Scanning source files..."):
        usages = scan_directory(path.resolve())

    required: set[str] = {u.name for u in usages}
    defined: set[str] = set(parse_dotenv(env_file_path).keys())

    missing = sorted(required - defined)
    extra = sorted(defined - required)
    present = sorted(required & defined)

    if missing:
        console.print(f"\n[red bold]Missing from {env_file_path.name}[/red bold] ({len(missing)})")
        for name in missing:
            console.print(f"  [red]x[/red]  {name}")

    if extra:
        console.print(
            f"\n[yellow bold]Defined but not found in code[/yellow bold] ({len(extra)})"
        )
        for name in extra:
            console.print(f"  [yellow]![/yellow]  {name}")

    if present:
        console.print(f"\n[green bold]Present and used[/green bold] ({len(present)})")
        for name in present:
            console.print(f"  [green]ok[/green]  {name}")

    console.print()
    if not missing:
        console.print("[green]All required variables are defined.[/green]")
    else:
        console.print(
            f"[red]{len(missing)} required variable(s) missing from {env_file_path.name}.[/red]"
        )


@env.command()
@click.argument("path", default=".", type=click.Path(exists=True, file_okay=False, path_type=Path))
@click.option("--output", default=".env.example", show_default=True, help="Output file path.")
@click.option("--force", is_flag=True, help="Overwrite if file already exists.")
def generate(path: Path, output: str, force: bool) -> None:
    """Generate a .env.example from discovered env var usage."""
    out_path = Path(output) if Path(output).is_absolute() else path.resolve() / output

    if out_path.exists() and not force:
        console.print(
            f"[yellow]{out_path.name} already exists. Use --force to overwrite.[/yellow]"
        )
        return

    with console.status("Scanning source files..."):
        usages = scan_directory(path.resolve())

    if not usages:
        console.print("[yellow]No environment variable usage found.[/yellow]")
        return

    names = sorted({u.name for u in usages})
    lines = ["# Generated by clude env generate", ""]
    for name in names:
        lines.append(f"{name}=")

    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    console.print(
        f"[green]ok[/green]  Wrote [bold]{len(names)}[/bold] variable(s) to [cyan]{out_path.name}[/cyan]"
    )
